version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: